# Generated by Django 4.1.10 on 2023-08-14 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Selection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Selection id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Selection name.", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "name_slug",
                    models.SlugField(
                        help_text="Selection name slug. This is unique to owner's scope.",
                        max_length=100,
                        verbose_name="name slug",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation date.",
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last modification date.",
                        verbose_name="modified",
                    ),
                ),
            ],
            options={
                "verbose_name": "selection",
                "verbose_name_plural": "selections",
                "db_table": "selection",
            },
        ),
    ]
