# Generated by Django 4.1.10 on 2023-08-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("selection", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectsection",
            name="selection",
        ),
        migrations.RemoveField(
            model_name="subjectsection",
            name="subject",
        ),
        migrations.DeleteModel(
            name="SectionSchedule",
        ),
        migrations.DeleteModel(
            name="SubjectSection",
        ),
        migrations.DeleteModel(
            name="Weekday",
        ),
    ]
