# Generated by Django 4.1.10 on 2023-08-14 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("selection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Subject id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Subject code",
                        max_length=7,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Subject name",
                        max_length=255,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "credits",
                    models.IntegerField(
                        default=0,
                        help_text="Subject credits",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="credits",
                    ),
                ),
                (
                    "is_lab",
                    models.BooleanField(
                        default=False,
                        help_text="Is this section a laboratory?",
                        verbose_name="is_lab",
                    ),
                ),
            ],
            options={
                "verbose_name": "subject",
                "verbose_name_plural": "subjects",
                "db_table": "subject",
            },
        ),
        migrations.CreateModel(
            name="Weekday",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Weekday id.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Weekday name.",
                        max_length=10,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "weekday",
                "verbose_name_plural": "weekdays",
                "db_table": "weekday",
            },
        ),
        migrations.CreateModel(
            name="SubjectSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Subject's section id.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "section",
                    models.IntegerField(
                        default=1,
                        help_text="Subject's section.",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="section",
                    ),
                ),
                (
                    "professor",
                    models.CharField(
                        help_text="Professor's name",
                        max_length=60,
                        verbose_name="professor",
                    ),
                ),
                (
                    "taken",
                    models.BooleanField(
                        default=False,
                        help_text="Are you going to take this subject?",
                        verbose_name="taken",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        help_text="Selection's id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_section",
                        related_query_name="subject_section",
                        to="selection.selection",
                        verbose_name="selection",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject's id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_section",
                        related_query_name="subject_section",
                        to="subject.subject",
                        verbose_name="subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "subject section",
                "verbose_name_plural": "subject sections",
                "db_table": "subject_section",
            },
        ),
        migrations.CreateModel(
            name="SectionSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        help_text="Section's schedule id.",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "start_time",
                    models.IntegerField(
                        default=6,
                        help_text="Section's start time.",
                        validators=[
                            django.core.validators.MinValueValidator(6),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="start time",
                    ),
                ),
                (
                    "end_time",
                    models.IntegerField(
                        default=8,
                        help_text="Section's end time.",
                        validators=[
                            django.core.validators.MinValueValidator(8),
                            django.core.validators.MaxValueValidator(22),
                        ],
                        verbose_name="end time",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Section's id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        related_query_name="schedule",
                        to="subject.subjectsection",
                        verbose_name="selection",
                    ),
                ),
                (
                    "weekday",
                    models.ForeignKey(
                        help_text="Weekday id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="weekday",
                        related_query_name="weekday",
                        to="subject.weekday",
                        verbose_name="weekday",
                    ),
                ),
            ],
            options={
                "verbose_name": "section schedule",
                "verbose_name_plural": "section schedules",
                "db_table": "section_schedule",
            },
        ),
    ]
