from .post_save_syllabus import post_save_syllabus
from .post_save_syllabus_subject import post_save_syllabus_subject
from .post_delete_syllabus import post_delete_syllabus
from .post_delete_syllabus_subject import post_delete_syllabus_subject
from .pre_save_syllabuses_fixture import pre_save_syllabuses_fixture
from .pre_save_syllabuses_subjects_fixture import (
    pre_save_syllabuses_subjects_fixture,
)
