# Generated by Django 4.1.10 on 2023-08-11 19:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("selection", "0003_remove_subjectsection_selection_and_more"),
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weekday",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubjectSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "section",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("professor", models.CharField(max_length=60)),
                ("taken", models.BooleanField(default=False)),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="selection.selection",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subject.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "start_time",
                    models.IntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(7),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "end_time",
                    models.IntegerField(
                        default=9,
                        validators=[
                            django.core.validators.MinValueValidator(9),
                            django.core.validators.MaxValueValidator(22),
                        ],
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_schedule",
                        to="subject_section.subjectsection",
                    ),
                ),
                (
                    "weekday",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="subject_section.weekday",
                    ),
                ),
            ],
        ),
    ]
