name: Code checks
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  lint:
    name: Lint test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8
  test:
    name: Code tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test
        run: python manage.py test
